version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build: 
      dockerfile: DatabaseDockerfile
      context: .
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    # ports:
    #   - "10100:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

